language: scala
sudo: required
dist: trusty

scala:
  - 2.11.12
  - 2.12.5

jdk:
  - oraclejdk8

before_install:
  - pip install --user codecov

script:
  - sbt +test
  - sbt clean coverage test

after_success:
  - codecov
